import type { NextPage } from 'next'
import Link from 'next/link'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Header from '../components/Header/Header'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Star Wars Wiki App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <main>
        <div className="container">
          <h2>Available categories</h2>
        <ul className='pages-list'>
          <li>
            <Link href="/planets">
              <a className='button-link'>Planets list</a>
            </Link>
          </li>
        </ul>
        </div>
        
      </main>
    </div>
  )
}

export default Home
