import type { NextPage } from 'next'
import Link from 'next/link'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Star Wars Wiki App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <h1>
          Welcome to Star Wars Wiki App
        </h1>
      </header>
      <main>
        <h2>Pages</h2>
        <ul>
          <li>
            <Link href="/planets">
              <a>Planets list</a>
            </Link>
          </li>
        </ul>
      </main>
    </div>
  )
}

export default Home
